### ISSUE TITLE
Incompatibility with Java 7 project

### ISSUE THREAD

**Issue by xixibun** [zalando-stups/stups-spring-oauth2-support#12]
Hi ,
we are calling this library from legacy customer component with java7,having the following error
java.lang.UnsupportedClassVersionError: org/zalando/stups/oauth2/spring/client/StupsTokensAccessTokenProvider : Unsupported major.minor version 52.0
this exception may mean that the maven dependency built and deployed by java 8,since parent is java8.
could you create a java7 version for supporting us.

**Comment by sarnowski** [comment]
The underlying library [tokens](https://github.com/zalando-stups/tokens) is also not supporting Java7 anymore. [Java7 is end-of-life since May 2015](https://www.java.com/en/download/faq/java_7.xml). We do not plan to support unmaintained Java versions currently.

**Comment by jbellmann** [comment]
@xixibun 

can you please post which version you use in your project?

**Comment by harti2006** [comment]
FYI: the "tokens" library is JDK 7 compatible since version 0.9.1

**Comment by xixibun** [comment]
@jbellmann 
jdk1.7.0_60
and our spring-core 3.2.3.RELEASE is not compatible with the your spring-boot version

**Comment by jbellmann** [comment]
@xixibun 

please try out version 1.0.4. It builds successfully against jdk7 and jdk8 [on travis](https://travis-ci.org/zalando-stups/stups-spring-oauth2-support/builds/87575269).

If you have more/other issues let us know.
If it works, close this issue please.

**Comment by jbellmann** [comment]
@xixibun 

Any news on this?
Otherwise we close this issue next week.

**Comment by xixibun** [comment]
it works fine now ,pls close the ticket,thx very much.
