### ISSUE TITLE
Using scope property for tokeninfo

### ISSUE THREAD

**Issue by jans510** [zalando-stups/stups-spring-oauth2-support#13]
I'm using this server tools together with the oauth provider mock https://github.com/zalando-stups/mocks.

On requesting the token info, the mock serves a 'scopes' property (line 210 in server.js) but a 'scope' property is needed (LaxAuthenticationExtractor class line 52 https://github.com/zalando-stups/stups-spring-oauth2-support/blob/master/stups-spring-oauth2-server/src/main/java/org/zalando/stups/oauth2/spring/server/LaxAuthenticationExtractor.java).

I don't know where to fix it best.

**Comment by jbellmann** [comment]
Hi Jan,

it's as implemented here ('scope', not 'scopes').

An example from our tech-wiki:
````
{
  "scope": ["fancy_scope.write","another_scope.read"],
  "grant_type":"password",
  "token_type":"Bearer",
  "expires_in":3599,
  "access_token":"$TOKEN",
}
```

Also talked with @prayerslayer, he will update the mocks.
