### ISSUE TITLE
Treat token failure as unauthorized

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-stups/stups-spring-oauth2-support#16]
Currently the `TokenInfoResourceServerTokenServices` throws a `TokenInfoEndpointException` in case there is an unspecific `Exception` when getting the token information (see `TokenInfoEndpointException#loadAuthentication`).

`TokenInfoEndpointException` is defined as a `AuthenticationException`. The corresponding `OAuth2AuthenticationProcessingFilter` works on `OAuth2Exception`s (see [here](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/authentication/OAuth2AuthenticationProcessingFilter.java#L161)). Therefore request that could not been authenticated (due to an exception retrieving the token information) are processed further.

To prevent that from happening `TokenInfoEndpointException` should extend `OAuth2Exception` instead.

**Comment by jbellmann** [comment]
Done with [1.0.6](https://github.com/zalando-stups/stups-spring-oauth2-support/releases/tag/1.0.6)
