### ISSUE TITLE
Avoid using query-parameter when retrieving access-token-info

### ISSUE THREAD

**Issue by jbellmann** [zalando-stups/stups-spring-oauth2-support#19]

**Comment by lukasniemeier-zalando** [comment]
Can be closed, right?

**Comment by jbellmann** [comment]
Yes, we use 'Authorization'-Header now.
And for reference the issue was also [fixed in the Spring-Framework](https://jira.spring.io/browse/SPR-13860)  and will be available with the RC1 for Spring 4.3
