### ISSUE TITLE
jackson1 and jackson2 dependencies

### ISSUE THREAD

**Issue by mastersimon** [zalando-stups/stups-spring-oauth2-support#29]
Hey guys,

as I can see you have both, jackson version 1 (org.codehaus.jackson) and jackson version 2 (com.fasterxml.jackson) as dependency.

Maybe you can try to get rid of the old version.

Best,
Simon

**Comment by jbellmann** [comment]
Sure, I will check that.

**Comment by jbellmann** [comment]
No, we can not remove that. It comes with 'spring-security-oauth2' and you can find imports for ['org.codehaus' for example here in the active codebase](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/common/util/JacksonJsonParser.java#L18).
