### ISSUE TITLE
Add annotation to create RestTemplate with required scopes.

### ISSUE THREAD

**Issue by aakavalevich** [zalando-stups/stups-spring-oauth2-support#33]
As a developer i would like to have an annotation(for example WithTokenId), 
so that i would be able to use RestTemplate without duplication like

```
@Bean
public PieroneOperations pieroneOperations(@Value("${pierone.url}") String pieroneBaseUrl) {
        return new RestTemplatePieroneOperations(buildOAuth2RestTemplate("pierone"), pieroneBaseUrl);
} 
private RestOperations buildOAuth2RestTemplate(final String tokenName) {
 return new StupsOAuth2RestTemplate(new StupsTokensAccessTokenProvider(tokenName, accessTokens));
} 
```
 
It should be possible to use like
```
@WithTokenId("pierone")
private RestTemplate pieroneRestTemplate

```

**Comment by jbellmann** [comment]
@aakavalevich 

I formatted your issue-description. Please use supported format option.

**Comment by jbellmann** [comment]
@aakavalevich 

Where is the duplication in your code, I don't see it?

**Comment by aakavalevich** [comment]
@jbellmann 
It's not in my code. I meant, that every client has to write the first code snippet instead of being able to write just the second snippet. It's duplication between clients.

**Comment by jbellmann** [comment]
@aakavalevich 

Are you using Spring-Boot?

**Comment by aakavalevich** [comment]
@jbellmann 
Yes.

**Comment by jbellmann** [comment]
Then please go over to [spring-boot-zalando-stups-tokens](https://github.com/zalando-stups/spring-boot-zalando-stups-tokens) and use version 0.9.11.M1 (should available in maven-central). Then you can do the following:
For field-injection (as in your example):

```
    @OAuth2RestOperationsAutowired("firstService")
    private RestOperations firstServiceRestOperations;
```
or as an 'Qualifier' only, maybe on constructor:

```
(..., @OAuth2RestOperations("firstService") RestOperations firstServiceRestOperations, ...)
```

The 'tokenId'/'serviceId' is mandantory.

Try it and let me know what is good, what is bad, how to improve it.

**Comment by ePaul** [comment]
@jbellmann I tried that ... I get a Bean Creation Exception. (I guess I'll open an issue over there, though I didn't find any documentation which says it should work, other than this here.)

**Comment by jbellmann** [comment]
@ePaul 
was just a first implementation, it's an 'M1' (Milestone-1) to get it into maven-central. Open an [issue there](https://github.com/zalando-stups/spring-boot-zalando-stups-tokens/issues) will be fine.
