### ISSUE TITLE
In case of 401 response from TokenInfoService TokenInfoResourceServerTokenServices throw HttpClientErrorException

### ISSUE THREAD

**Issue by aakavalevich** [zalando-stups/stups-spring-oauth2-support#38]
In case of 401 as a status of a response from TokenInfoService  TokenInfoResourceServerTokenServices throws HttpClientErrorException, so service response will be 500. 
To prevent this, HttpClientErrorException should be catched and InvalidTokenException thrown. 
It can be catched around line 67 in DefaultTokenInfoRequestExecutor.

**Comment by jbellmann** [comment]
@aakavalevich 
can you please provide how you setup the TokenInfoResourceServerTokenServices instance?
Seems to me you are missing the correct ResponseErrorHandler. Have a look [here](https://github.com/zalando-stups/stups-spring-oauth2-support/blob/issue_38/stups-spring-oauth2-server/src/test/java/org/zalando/stups/oauth2/spring/server/Issue_38_Test.java). Without the correct ResponseErrorHandler it behaves as described in your issue.
