### ISSUE TITLE
Support for custom roles in TokenInfoResourceServerTokenServices

### ISSUE THREAD

**Issue by mkunz** [zalando-stups/stups-spring-oauth2-support#42]
It should be possible to provide a list of roles in TokenInfoResourceServerTokenServices that is then checked in the spring security filter chain if the request is authorized.

**Comment by hjacobs** [comment]
@mkunz do you mean OAuth scopes? You can/should use the expression language `#oauth2.hasScope('foo')`

**Comment by jbellmann** [comment]
@hjacobs no, he really means 'roles' in this case. We discussed it this afternoon. Regarding the 'realm' of the token, they want to be able to request data from another service to provide information about 'ROLES' in the 'UsernamePasswordAuthenticationToken'-object.

**Comment by jbellmann** [comment]
I think this feature is already out, right?

Please reopen the ticket if I'm wrong.

Thanks for contributing.
Regards
Jörg
