### ISSUE TITLE
Configuration of RestTemplate in TokenInfoResourceServerTokenServices

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando-stups/stups-spring-oauth2-support#7]
*TokenInfoResourceServerTokenServices* [creates its own](https://github.com/zalando-stups/stups-spring-oauth2-support/blob/master/stups-spring-oauth2-server/src/main/java/org/zalando/stups/oauth2/spring/server/TokenInfoResourceServerTokenServices.java#L72) *OAuthRestTemplate* and does not expose any method of configuring the instance. One of many use cases for this would be adding interceptors for logging.

One could take the chance and use a [StupsOAuth2RestTemplate](https://github.com/zalando-stups/stups-spring-oauth2-support/blob/master/stups-spring-oauth2-client/src/main/java/org/zalando/stups/oauth2/spring/client/StupsOAuth2RestTemplate.java) instead.

**Comment by jbellmann** [comment]
Hi Lukas,

in our latest release we provide more constructors for TokenInfoResourceServerTokenServices. It's now also possible to create an RestTemplate (it's not an OAuth2RestTemplate anymore, be aware of that) in your code and and pass that as an argument.
Do you think that fixes this issue?

Cheers
Jörg

**Comment by lukasniemeier-zalando** [comment]
I am not sure about the usage of a non `OAuth2RestTemplate` inside a `ResourceServerTokenServices` since there is quite a lot of code relying on proper `OAuth2Exception` (which are deserialized and thrown by the error handler of the `OAuth2RestTemplate`).

**Comment by jbellmann** [comment]
Hi Lukas,

any news on this? Should we come together for discussion?

**Comment by aakavalevich** [comment]
I need RestTemplate to pass also flow_id in the headers. What is the recommended way to do that?

**Comment by jbellmann** [comment]
A good way would be to use [ClientHttpRequestInterceptor](http://docs.spring.io/spring/docs/4.2.5.RELEASE/javadoc-api/org/springframework/http/client/ClientHttpRequestInterceptor.html). And here is a concrete example on how to add an Request-Header into it. [In this case, the Authorization-Header](https://github.com/spring-projects/spring-social/blob/master/spring-social-core/src/main/java/org/springframework/social/oauth2/PreemptiveBasicAuthClientHttpRequestInterceptor.java). And to share the 'FLOWID' around during request use something like [MDC](https://github.com/zalando/planb-provider/blob/master/src/main/java/org/zalando/planb/provider/RequestInfoMDCFilter.java)

**Comment by jbellmann** [comment]
I think, nobody cares about this issue. No comments. I will close it.
